name: Python CI Week 0
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned successfully."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest tests/test_extract_dataframe.py
